import Head from "next/head";
import type { NextPage } from "next";

const HeadMeta: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TOSv2 - Tokamak</title>
        <meta property="og:type" content="website" />

        <meta
          property="og:url"
          content="https://goerli.tosv2.tokamak.network"
        />
        <meta property="title" content="TOSv2 - Tokamak" />
        <meta property="og:title" content="TOSv2 - Tokamak" />
        <meta
          property="description"
          content="Functional upgrade to TONStarter ecosystem"
        />
        <meta
          property="og:description"
          content="Functional upgrade to TONStarter ecosystem"
        />
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default HeadMeta;
