import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BasicButton from "./components/buttons/BasicButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex fontSize={100}>FONT TEST</Flex>
      <BasicButton name="test"></BasicButton>
    </div>
  );
};

export default Home;
