import { Flex } from "@chakra-ui/react";
import CustomCheckBox from "common/input/CustomCheckBox";
import TextInput from "common/input/TextInput";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BasicButton from "./common/button/BasicButton";
import SubmitButton from "./common/button/SubmitButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TOSv2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex></Flex>
    </div>
  );
};

export default Home;
