import { Flex } from "@chakra-ui/react";
import CheckBox from "components/input/CheckBox";
import TextInput from "components/input/TextInput";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BasicButton from "./components/button/BasicButton";
import SubmitButton from "./components/button/SubmitButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex fontSize={100} flexDir={"column"}>
        FONT TEST
        <Flex minH={"60vh"}>
          <Flex flexDir={"column"} mr={5} justifyContent="space-between">
            <BasicButton name="Button"></BasicButton>
            <BasicButton name="Button" isDisabled={true}></BasicButton>
            <SubmitButton name="Submit"></SubmitButton>
            <SubmitButton name="Submit" isDisabled={true}></SubmitButton>
            <SubmitButton name="Submit" isLoading={true}></SubmitButton>
          </Flex>
          <Flex flexDir={"column"} mr={5} justifyContent="space-between">
            <TextInput placeHolder="Placeholder"></TextInput>
            <TextInput value={"Value"}></TextInput>
            <TextInput value={"Error"} isError={true}></TextInput>
            <CheckBox></CheckBox>
          </Flex>
        </Flex>
      </Flex>
    </div>
  );
};

export default Home;
